export default [
  {
    key: 'pokedex',
    title: 'Pokédex',
    description: `PokéAPI client that enables users to search a pokémon by name, and then displays the sprite of said pokémon.`,
    learned: [
      'Pour my Fetch API experience into React.',
      'React Hooks.',
      'Live Search.',
    ],
    technologies: ['React', 'Redux', 'Material UI', 'React Live Search'],
    repository: 'https://github.com/Progressandro/React-Pokedex',
    image: 'pokedex.png',
  },
  {
    key: 'hangman',
    title: 'Hangman Game',
    description: `Classic Hangman game that let's you review your choices and "time-travel" back to any step. I built this to practice state management in React.`,
    learned: [
      'Material UI usage with React.',
      'State Management.',
      'Conditional Rendering.',
    ],
    technologies: ['React', 'Material UI'],
    repository: 'https://github.com/Progressandro/hangman-react',
    image: 'hangman.png',
  },
  {
    key: 'resume',
    title: 'Personal Resume',
    description: `Classic Hangman game that let's you review your choices and "time-travel" back to any step. I built this to practice state management in React.`,
    learned: [
      'Deeper understanding about React Router.',
      'Advanced Layouts in React.',
      'Material UI Sidebar Component implementation.',
    ],
    technologies: ['React', 'Material UI'],
    repository: 'https://github.com/Progressandro/progressandro.github.io',
    image: '',
  },
  {
    key: 'instadvice',
    title: 'Instadvice [In Progress]',
    description: `Get a random advice, like or dislike it, save your favorites and check the community's greatest advices.`,
    learned: [
      'MERN Stack based Back-End development.',
      'Front-End<->Backend Communication in MERN.',
      'Postman basic usage.',
    ],
    technologies: [
      'React',
      'Material UI',
      'MongoDB',
      'Express',
      'Node',
      'Postman',
    ],
    repository: 'https://github.com/Progressandro/instadvice',
    image: 'instadvice.png',
  },
  {
    key: 'restaurant',
    title: 'ConFusion Restaurant App',
    description: `App for a Restaurant, developed during Coursera's MERN Full-Stack Specialization course.`,
    learned: [
      'First interactions with React',
      'Flux architecture.',
      'Redux.',
      'Reactstrap usage.',
    ],
    technologies: ['React', 'Redux', 'Reactstrap', 'Redux-Thunk'],
    repository: 'https://github.com/Progressandro/Restaurant-React',
    image: 'restaurant.png',
  },
  {
    key: 'other',
    title: 'Other Projects',
    description: `The projects mentioned before are the ones that best describes what I'm aiming for at this point in time. However, there are many more that can be easily checked out at my Github Profile.`,
    learned: [
      'Numerical Methods[Python].',
      'Web Development[LAMP Stack].',
      'Pile, Stack & Queue. [C++]',
      'Binary Trees, N-Trees & Graphs. [C++]',
      'Etc.',
    ],
    technologies: [
      'Python',
      'C++',
      'Chrome Extensions',
      'PHP',
      'MySQL',
      'Apache',
    ],
    repository: 'https://github.com/Progressandro',
    image: '',
  },
];
